-d C:\Users\aylan\OneDrive\Belgeler\fpga_project_proje1\impl\gwsynthesis\fpga_project_proje1.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\aylan\OneDrive\Belgeler\fpga_project_proje1\src\fpga_project_proje1.cst
-cfg C:\Users\aylan\OneDrive\Belgeler\fpga_project_proje1\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
